# Generated by Django 5.1.6 on 2025-02-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='catering_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shopreg')),
            ],
        ),
        migrations.DeleteModel(
            name='CateringService',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
