# Generated by Django 5.1.6 on 2025-02-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_shopreg_remove_booking_catering_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopreg',
            new_name='servicereg',
        ),
        migrations.RenameModel(
            old_name='Register',
            new_name='userreg',
        ),
    ]
