# Generated by Django 5.1.6 on 2025-02-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicereg',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userreg',
            old_name='Email',
            new_name='email',
        ),
    ]
