# Generated by Django 5.1.6 on 2025-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_email_servicereg_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='service',
        ),
    ]
