# Generated by Django 5.1.6 on 2025-02-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_shop_product_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
